title: "Dr Qiao Su | Omics Science, Systems Biology"
name: "Dr Qiao Su"
description: "Systems Biology • Multi-Omics • Translational Research"
url: "https://iqiaosu.github.io"
baseurl: ""

# 使用 Minimal Mistakes 主题（GitHub Pages 支持）
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "default"   # 可选: air, contrast, dark, solarized, etc.

# 作者信息
author:
  name: "Dr Qiao Su"
  avatar: "/assets/images/avatar.jpg"   # 可先不传，传了就会显示
  bio: "Omics & Systems Biology • Disease Mechanisms • Biomarker Discovery"
  location: "China / Australia"
  email: "qiaosu.qs@gmail.com"
  links:
    - label: "GitHub"
      url: "https://github.com/iqiaosu"
      icon: "fab fa-github"
    - label: "Google Scholar"
      url: "https://scholar.google.com/"
      icon: "ai ai-google-scholar"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/"
      icon: "fab fa-linkedin"

# 导航
collections:
  pages:
    output: true
    permalink: /:path/

# 插件（GitHub Pages 支持的）
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: "/page:num/"

# 默认 Front Matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# SEO
logo: "/assets/images/avatar.jpg"
